/*
 * marvelcomics_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

package creators_pkg

import "marvelcomics_lib/models_pkg"

/*
 * Interface for the CREATORS_IMPL
 */
type CREATORS interface {
    GetCreatorIndividual (string) (*models_pkg.Creator, error)

    GetComicsCollectionByCreatorId (string, *string, *string, models_pkg.DateDescriptorEnum, *string, *string, *string, *string, *string, *string, models_pkg.FormatTypeEnum, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.ComicDataWrapper, error)

    GetCreatorEventsCollection (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.EventDataWrapper, error)

    GetCreatorSeriesCollection (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.SeriesDataWrapper, error)

    GetCreatorStoryCollection (string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.StoryDataWrapper, error)

    GetCreatorCollection (*string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.CreatorDataWrapper, error)
}

/*
 * Factory for the CREATORS interaface returning CREATORS_IMPL
 */
func NewCREATORS() CREATORS {
    return &CREATORS_IMPL{}
}