/*
 * marvelcomics_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

package characters_pkg

import "marvelcomics_lib/models_pkg"

/*
 * Interface for the CHARACTERS_IMPL
 */
type CHARACTERS interface {
    GetCharacterIndividual (string) (*models_pkg.Character, error)

    GetComicsCharacterCollection (string, *string, *string, models_pkg.DateDescriptorEnum, *string, *string, *string, *string, *string, *string, models_pkg.FormatTypeEnum, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.ComicDataWrapper, error)

    GetCharacterEventsCollection (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.EventDataWrapper, error)

    GetCharacterSeriesCollection (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.SeriesDataWrapper, error)

    GetCharacterStoryCollection (string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.StoryDataWrapper, error)

    GetCharacterCollection (*string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.CharacterDataWrapper, error)
}

/*
 * Factory for the CHARACTERS interaface returning CHARACTERS_IMPL
 */
func NewCHARACTERS() CHARACTERS {
    return &CHARACTERS_IMPL{}
}