/*
 * marvelcomics_lib
 *
 * This file was automatically generated by APIMATIC v2.0 on 05/25/2016
 */

package marvelcomics_lib

/** The base Uri for API calls */
const BASEURI string = "http://gateway.marvel.com/v1/public"

var Config struct {
    /** Replace the value of Referer with an appropriate value */
    Referer string
    /** Replace the value of Apikey with an appropriate value */
    Apikey string
}
