/*
 * marvelcomics_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */
package models_pkg

import(
	"encoding/json"
)

/**
 * Type definition for DateDescriptorEnum enum
 */
type DateDescriptorEnum int

/**
 * Value collection for DateDescriptorEnum enum
 */
const (
    DateDescriptorEnum_LASTWEEK DateDescriptorEnum = 1 + iota
    DateDescriptorEnum_NEXTWEEK
    DateDescriptorEnum_THISMONTH
    DateDescriptorEnum_THISWEEK
)

func (r DateDescriptorEnum) MarshalJSON() ([]byte, error) { 
	s := DateDescriptorEnumToValue(r)
 	return json.Marshal(s) 
} 

func (r *DateDescriptorEnum) UnmarshalJSON(data []byte) error { 
 	var s string 
 	json.Unmarshal(data, &s)
 	v :=  DateDescriptorEnumFromValue(s)
 	*r = v 
 	return nil 
 } 


/**
 * Converts DateDescriptorEnum to its string representation
 */
func DateDescriptorEnumToValue(dateDescriptorEnum DateDescriptorEnum) string {
	switch dateDescriptorEnum {
		case DateDescriptorEnum_LASTWEEK:
			return "lastWeek"		
		case DateDescriptorEnum_NEXTWEEK:
			return "nextWeek"		
		case DateDescriptorEnum_THISMONTH:
			return "thisMonth"		
		case DateDescriptorEnum_THISWEEK:
			return "thisWeek"		
        default:
        	return "lastWeek"
	}
}

/**
 * Converts DateDescriptorEnum Array to its string Array representation
*/
func DateDescriptorEnumArrayToValue(dateDescriptorEnum []DateDescriptorEnum) []string {
	convArray := make([]string,len( dateDescriptorEnum))
	for i:=0; i<len(dateDescriptorEnum);i++ {
		convArray[i] = DateDescriptorEnumToValue(dateDescriptorEnum[i])
	}
	return convArray
}


/**
 * Converts given value to its enum representation
 */
func DateDescriptorEnumFromValue(value string) DateDescriptorEnum {
	switch value {
		case "lastWeek":
			return DateDescriptorEnum_LASTWEEK
		case "nextWeek":
			return DateDescriptorEnum_NEXTWEEK
		case "thisMonth":
			return DateDescriptorEnum_THISMONTH
		case "thisWeek":
			return DateDescriptorEnum_THISWEEK
        default:
            return DateDescriptorEnum_LASTWEEK
	}
}
