/*
 * marvelcomics_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

package events_pkg

import "marvelcomics_lib/models_pkg"

/*
 * Interface for the EVENTS_IMPL
 */
type EVENTS interface {
    GetEventIndividual (string) (*models_pkg.Event, error)

    GetEventCharacterCollection (string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.CharacterDataWrapper, error)

    GetComicsCollectionByEventId (string, *string, *string, *string, models_pkg.DateDescriptorEnum, *string, *string, *string, *string, *string, *string, models_pkg.FormatTypeEnum, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.ComicDataWrapper, error)

    GetCreatorCollectionByEventId (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.CreatorDataWrapper, error)

    GetEventSeriesCollection (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.SeriesDataWrapper, error)

    GetEventStoryCollection (string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.StoryDataWrapper, error)

    GetEventsCollection (*string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.EventDataWrapper, error)
}

/*
 * Factory for the EVENTS interaface returning EVENTS_IMPL
 */
func NewEVENTS() EVENTS {
    return &EVENTS_IMPL{}
}