/*
 * marvelcomics_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

package stories_pkg

import "marvelcomics_lib/models_pkg"

/*
 * Interface for the STORIES_IMPL
 */
type STORIES interface {
    GetStoryIndividual (string) (*models_pkg.Story, error)

    GetCharacterCollectionByStoryId (string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.CharacterDataWrapper, error)

    GetComicsCollectionByStoryId (string, *string, *string, *string, models_pkg.DateDescriptorEnum, *string, *string, *string, *string, *string, *string, models_pkg.FormatTypeEnum, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.ComicDataWrapper, error)

    GetCreatorCollectionByStoryId (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.CreatorDataWrapper, error)

    GetEventsCollectionByStoryId (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.EventDataWrapper, error)

    GetStorySeriesCollection (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.SeriesDataWrapper, error)

    GetStoryCollection (*string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.StoryDataWrapper, error)
}

/*
 * Factory for the STORIES interaface returning STORIES_IMPL
 */
func NewSTORIES() STORIES {
    return &STORIES_IMPL{}
}