/*
 * marvelcomics_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

package series_pkg

import "marvelcomics_lib/models_pkg"

/*
 * Interface for the SERIES_IMPL
 */
type SERIES interface {
    GetSeriesIndividual (string) (*models_pkg.Series, error)

    GetSeriesCharacterWrapper (string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.CharacterDataWrapper, error)

    GetComicsCollectionBySeriesId (string, *string, *string, *string, models_pkg.DateDescriptorEnum, *string, *string, *string, *string, *string, *string, models_pkg.FormatTypeEnum, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.ComicDataWrapper, error)

    GetCreatorCollectionBySeriesId (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.CreatorDataWrapper, error)

    GetEventsCollectionBySeriesId (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.EventDataWrapper, error)

    GetSeriesStoryCollection (string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.StoryDataWrapper, error)

    GetSeriesCollection (*string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.SeriesDataWrapper, error)
}

/*
 * Factory for the SERIES interaface returning SERIES_IMPL
 */
func NewSERIES() SERIES {
    return &SERIES_IMPL{}
}