/*
 * marvelcomics_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 05/25/2016
 */

package comics_pkg

import "marvelcomics_lib/models_pkg"

/*
 * Interface for the COMICS_IMPL
 */
type COMICS interface {
    GetComicIndividual (string) (*models_pkg.Comic, error)

    GetComicCharacterCollection (string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.CharacterDataWrapper, error)

    GetCreatorCollectionByComicId (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.CreatorDataWrapper, error)

    GetIssueEventsCollection (string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.EventDataWrapper, error)

    GetComicStoryCollectionByComicId (string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.StoryDataWrapper, error)

    GetComicsCollection (*string, *string, *string, models_pkg.DateDescriptorEnum, *string, *string, *string, *string, *string, *string, models_pkg.FormatTypeEnum, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string, *string) (*models_pkg.ComicDataWrapper, error)
}

/*
 * Factory for the COMICS interaface returning COMICS_IMPL
 */
func NewCOMICS() COMICS {
    return &COMICS_IMPL{}
}